### ISSUE TITLE
Inconsistent license declarations

### ISSUE THREAD

**Issue by tianon** [kisielk/sqlstruct#10]
I'm looking at the `LICENSE` file and it's pretty clearly MIT/Expat, but the `.go` files have comments at the top mentioning "BSD style". :smile:

**Comment by kisielk** [comment]
The MIT license is a BSD-style license, but I changed the text in .go file to avoid any confusion.

**Comment by tianon** [comment]
Awesome, thanks for clarifying/adjusting!
